"""
meta_learn_node factory — light proposals at request time (spec §8).

Four proposal types:
  Light 1: investigate_divergence  — when alignment/reproduction diverge > 0.3
  Light 2: adjust_weight           — reinforce retrieval strategy on high-alignment outcome
  Light 3: investigate_rule        — when critic sees high reproduction but low rule conformance
  Light 4: investigate_new_rule    — high-confidence pattern with no governance coverage

Heavy proposals (modify/add/deprecate rules) are generated by the async outcome
processor when report_decision_outcome arrives — not here.

learning_weight encodes confidence in the signal:
  - off-baseline: 0.3  (atypical situation, weaker signal)
  - normal:       1.0
  - bootstrap:   *= 0.5 (sparse data, even weaker)
"""

from src.helpers.predicates import has_governance_coverage
from src.helpers.trace_utils import compress_state_for_persistence


def make_meta_learn_node(stores):
    def meta_learn_node(state):
        learning_weight = 0.3 if state["is_off_baseline"] else 1.0
        if state["is_bootstrap"]:
            learning_weight *= 0.5

        proposals = []

        # Light 1: Divergence signal
        if state["confidence_divergence"] > 0.3:
            proposals.append({
                "type": "investigate_divergence",
                "target_rule_id": None,
                "rationale": (
                    f"alignment={state['alignment_confidence']:.2f} "
                    f"reproduction={state['reproduction_confidence']:.2f}"
                ),
                "weight": learning_weight,
                "supporting_traces": [state["trace_id"]],
                "context": state["perceived_context"],
            })

        # Light 2: Retrieval strategy reinforcement
        if state["alignment_confidence"] > 0.85 and state.get("retrieval_strategy"):
            proposals.append({
                "type": "adjust_weight",
                "target_rule_id": f"retrieval_strategy:{state['retrieval_strategy']}",
                "rationale": "high-alignment outcome with this retrieval strategy",
                "weight": learning_weight,
                "delta": 0.05 * learning_weight,
                "supporting_traces": [state["trace_id"]],
                "context": state["perceived_context"],
            })

        # Light 3: Rule-conflict signal from critic
        for scored in state["alignment_scores"].get("hypotheses", []):
            if (
                scored["reproduction_confidence"] > 0.7
                and scored["rule_conformance_score"] < 0.3
                and scored["rule_conflict_details"]
            ):
                for conflict in scored["rule_conflict_details"]:
                    proposals.append({
                        "type": "investigate_rule",
                        "target_rule_id": conflict["rule_id"],
                        "rationale": "high_reproduction_violation",
                        "weight": learning_weight,
                        "supporting_traces": [state["trace_id"]],
                        "context": state["perceived_context"],
                    })

        # Light 4: Pattern emergence
        active_rules = state.get("active_governance_rules") or []
        if (
            state["alignment_confidence"] > 0.85
            and state["reproduction_confidence"] > 0.85
            and not has_governance_coverage(state["perceived_context"], active_rules)
        ):
            proposals.append({
                "type": "investigate_new_rule",
                "target_rule_id": None,
                "rationale": "high-confidence pattern with no governance coverage",
                "weight": learning_weight,
                "supporting_traces": [state["trace_id"]],
                "context": state["perceived_context"],
            })

        for p in proposals:
            stores.proposals.add(user_id=state["user_id"], proposal=p)

        if state.get("trace_persist_required"):
            stores.traces.save(
                state["trace_id"],
                compress_state_for_persistence(state),
            )

        pending_review = (
            state["sparse_domain_flag"] is not None
            or state["confidence_divergence"] > 0.3
            or state["is_off_baseline"]
        )
        return {
            "proposed_governance_updates": proposals,
            "pending_reversal_check": pending_review,
        }

    return meta_learn_node
